const accessories = [
	{
		id: "1",
		productName: "Blue Daisy Shoelaces Tube",
		productCategory: "All Shoes",
		pricing: "8.99",
		image: "/productImages/Blue Daisy Shoelaces Tube.jpg",
	},
	{
		id: "2",
		productName: "Pink Daisy Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Pink Daisy Shoelaces.jpg",
	},
	{
		id: "3",
		productName: "Pink & Blue Daisy Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/PinkBlue Daisy Shoelaces.jpg",
	},
	{
		id: "4",
		productName: "Takashi Sunflower Brooch",
		productCategory: "All Shoes",
		pricing: "7.95",
		image: "/productImages/Sunflowers Rainbow Brooch Pins.jpg",
	},
	{
		id: "5",
		productName: "Pink Daisy Shoelaces Tube",
		productCategory: "All Shoes",
		pricing: "8.99",
		image: "/productImages/Pink Daisy Shoelaces Tube.jpg",
	},
	{
		id: "6",
		productName: "White Daisy Shoelaces Tube",
		productCategory: "All Shoes",
		pricing: "8.99",
		image: "/productImages/White Daisy Shoelaces Tube.jpg",
	},
	{
		id: "7",
		productName: "White & Pink Daisy Shoelaces Tube",
		productCategory: "All Shoes",
		pricing: "8.99",
		image: "/productImages/White Pink Daisy Shoelaces Tube.jpg",
	},
	{
		id: "8",
		productName: "Black Daisy Shoelaces Tube",
		productCategory: "All Shoes",
		pricing: "8.99",
		image: "/productImages/Black Daisy Shoelaces Tube.jpg",
	},
	{
		id: "9",
		productName: "Flatties Black Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Flatties_Black.jpg",
	},
	{
		id: "10",
		productName: "Flatties Bright Orange Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Flatties_BrightOrange.jpg",
	},
	{
		id: "11",
		productName: "Flatties Green Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Flatties_Green.jpg",
	},
	{
		id: "12",
		productName: "Flatties Lipstick Pink Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Flatties_LipstickPink.jpg",
	},
	{
		id: "13",
		productName: "Flatties_White Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Flatties_White.jpg",
	},
	{
		id: "14",
		productName: "Flatties Violet Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Flatties_Violet.jpg",
	},
	{
		id: "15",
		productName: "Flatties Red Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Flatties_Red.jpg",
	},
	{
		id: "16",
		productName: "Flatties Purple Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "/productImages/Flatties_Purple.jpg",
	},
	{
		id: "17",
		productName: "All Daisy Tube Shoelaces",
		productCategory: "All Shoes",
		pricing: "34.99",
		image: "/productImages/Black Daisy Shoelaces Tube.jpg",
	},
	{
		id: "18",
		productName: "All Flatties Shoelaces",
		productCategory: "All Shoes",
		pricing: "24.99",
		image: "/productImages/Pink Daisy Shoelaces.jpg",
	},
];
export default accessories;
