const accessories = [
	{
		id: "1",
		productName: "Takashi Sunflower Brooch",
		productCategory: "All Shoes",
		pricing: "7.99",
		image: "Sunflowers Rainbow Brooch Pins.jpg",
	},
	{
		id: "2",
		productName: "White & Pink Daisy Shoelaces",
		productCategory: "Men & Womens",
		pricing: "9.99",
		image: "_MG_382.jpg",
	},
	{
		id: "3",
		productName: "Black & White Daisy Shoelaces",
		productCategory: "Men & Womens",
		pricing: "9.99",
		image: "_MG_3829-2.jpg",
	},
	{
		id: "4",
		productName: "White & Turquoise Daisy Shoelaces",
		productCategory: "Men & Womens",
		pricing: "9.99",
		image: "_MG_3859.jpg",
	},
	{
		id: "5",
		productName: "White & Blue Daisy Shoelaces",
		productCategory: "Men & Womens",
		pricing: "9.99",
		image: "_MG_3923.jpg",
	},
	{
		id: "6",
		productName: "White & Red Daisy Shoelaces",
		productCategory: "Men & Womens",
		pricing: "9.99",
		image: "_MG_3948.jpg",
	},
	{
		id: "7",
		productName: "White & Yellow Daisy Shoelaces",
		productCategory: "Men & Womens",
		pricing: "9.99",
		image: "_MG_3828.jpg",
	},
	{
		id: "8",
		productName: "White & Green Daisy Shoelaces",
		productCategory: "Men & Womens",
		pricing: "9.99",
		image: "_MG_3843.jpg",
	},
	{
		id: "9",
		productName: "White & Black Daisy Shoelaces",
		productCategory: "Men & Womens",
		pricing: "9.99",
		image: "_MG_3890.jpg",
	},
	{
		id: "10",
		productName: "Flatties Black Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "Flatties_Black.jpg",
	},
	{
		id: "11",
		productName: "Flatties Bright Orange Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "Flatties_BrightOrange.jpg",
	},
	{
		id: "12",
		productName: "Flatties Green Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "Flatties_Green.jpg",
	},
	{
		id: "13",
		productName: "Flatties Lipstick Pink Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "Flatties_LipstickPink.jpg",
	},
	{
		id: "14",
		productName: "Flatties_White Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "Flatties_White.jpg",
	},
	{
		id: "15",
		productName: "Flatties Violet Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "Flatties_Violet.jpg",
	},
	{
		id: "16",
		productName: "Flatties Red Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "Flatties_Red.jpg",
	},
	{
		id: "17",
		productName: "Flatties Purple Shoelaces",
		productCategory: "All Shoes",
		pricing: "3.99",
		image: "Flatties_Purple.jpg",
	},
];
export default accessories;
