const shoeProducts = [
	{
		id: "1",
		productName: "Fire Force - Shinra Kusakabe",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_3143-2.jpg",
	},
	{
		id: "2",
		productName: "My Neighbor Totoro",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_3102.jpg",
	},
	{
		id: "3",
		productName: "Tanjiro, Zenitsu & Inosuke",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_2330.jpg",
	},
	{
		id: "4",
		productName: "One Punch Man - Garou",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_3070.jpg",
	},
	{
		id: "5",
		productName: "Naruto - Sasuke Uchiha",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_2619.jpg",
	},
	{
		id: "6",
		productName: "Goku Vs Vegeta",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_3021.jpg",
	},
	{
		id: "7",
		productName: "Spirited Away Castle",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_2778.jpg",
	},
	{
		id: "8",
		productName: "Powerpuff Girls",
		productCategory: "Womens",
		pricing: "199.95",
		image: "_MG_3098.jpg",
	},
	{
		id: "9",
		productName: "Spirited Away & My Neighbor Totoro",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_1629-3.jpg",
	},
	{
		id: "10",
		productName: "Bleach - Ichigo Kurosaki",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_3269.jpg",
	},
	{
		id: "11",
		productName: "Haikyuu!! - Tetsuro Kuroo",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_3644.jpg",
	},
	{
		id: "12",
		productName: "Haikyuu!!",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_3441.jpg",
	},
	{
		id: "13",
		productName: "Spider-Man: Miles Morales",
		productCategory: "Mens & Womens",
		pricing: "2,299.95",
		image: "_MG_3295.jpg",
	},
	{
		id: "14",
		productName: "Demon Slayer - Mitsuri Kanroji",
		productCategory: "Womens",
		pricing: "199.95",
		image: "_MG_3551.jpg",
	},
	{
		id: "15",
		productName: "Naruto - Sakura, Naruto, Sasuke",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_3482.jpg",
	},
	{
		id: "16",
		productName: "Hunter × Hunter - Killua Zoldyck",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "_MG_2538.jpg",
	},
	{
		id: "17",
		productName: "Ochaco Uraraka",
		productCategory: "Womens",
		pricing: "199.95",
		image: "_MG_2702.jpg",
	},
	{
		id: "18",
		productName: "High-Top - Brown",
		productCategory: "Mens & Womens",
		pricing: "249.95",
		image: "Pull&Bear - Contrast High-Top Brown.jpg",
	},
	{
		id: "19",
		productName: "High-Top - Grey",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "Pull&Bear - Contrast High-Top Grey.jpg",
	},
	{
		id: "20",
		productName: "High-Top - Black & White",
		productCategory: "Mens & Womens",
		pricing: "199.95",
		image: "Pull&Bear - Contrast High-Top Black & White.jpg",
	},
	{
		id: "21",
		productName: "Chunky Soles - White",
		productCategory: "Mens & Womens",
		pricing: "119.95",
		image: "Pull&Bear - Chunky Soles White.jpg",
	},
];

export default shoeProducts;
