import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import {motion} from "framer-motion";
import Navbar from "/components/Navbar";
import FooterLight from "/components/alternativeStyling/FooterLight";
import styles from "/styles/Home.module.scss";

const Brand = () => {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>ToddBlue | United Kingdom</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/otherImages/ms-icon-310x310.jpg" />

				{/* <!-- AOS CDN.js Reveal Animation  --> */}
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
					integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
					crossOrigin="anonymous"
					referrerpolicy="no-referrer"
				/>
				{/* <!-- Bootstrap CSS --> */}
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
					crossOrigin="anonymous"
				/>
				{/* <!-- Bootstrap Icon Link --> */}
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
				/>
				{/* <!-- Icons for Mobile viewport --> */}
				<link
					rel="stylesheet"
					href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
				/>
			</Head>

			{/* <!--===== NAVIGATION =====--> */}
			<Navbar />

			<div className={styles.BrandMain}>
				{/* <!--===== HERO =====--> */}
				<div className={styles.backgroundImageTop}>
					<div className="container">
						<div className={styles.content}>
							<div className={styles.title}>
								<h2>Our Story</h2>
								<h5>One of a kind global street-wear shoes & merchandise</h5>
							</div>
						</div>
					</div>
				</div>

				<div>
					<div className="container">
						<div className={styles.content}>
							<div className={styles.leftSide}>
								<div className={styles.title}>
									<h2>Our Story</h2>
									<h5>One of a kind global street-wear shoes & merchandise</h5>
								</div>
							</div>
							<div className={styles.rightSide}>
								<Link href="#" target="blank">
									<a>
										<Image
											src="/otherImages/ad5893bc646b1badc82e1f2a7a4689aa.jpg"
											alt="Product Image"
											width={500}
											height={200}
											layout="responsive"
											objectFit="contain"
										></Image>
									</a>
								</Link>
							</div>
						</div>
					</div>
				</div>
			</div>

			{/* <!--===== FOOTER =====--> */}
			<FooterLight />
		</motion.div>
	);
};

export default Brand;
