/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import {motion} from "framer-motion";
import styles from "/styles/Home.module.scss";
import NewProduct from "/lib/newProduct";
import animation from "/animation/animation.js";
import ProductDisplayFourGrid from "/components/productDisplayFourGrid";

const New = () => {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>New Products | ToddBlue</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/otherImages/ms-icon-310x310.jpg" />
				{/* <!-- Bootstrap CSS --> */}
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
					crossOrigin="anonymous"
				/>
				{/* <!-- Bootstrap Icon Link --> */}
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
				/>
				{/* <!-- Icons for Mobile viewport --> */}
				<link
					rel="stylesheet"
					href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
				/>
			</Head>

			<main className={styles.main}>
				<div className={styles.new}>
					<div className={styles.borderLineMid}></div>

					<h2>New Drip</h2>

					{/* <!--===== NEW PRODUCTS =====--> */}
					<ProductDisplayFourGrid data={NewProduct} />

					{/* <!--===== TRENDING BRANDS =====--> */}
					<div className={styles.trendingBrands}>
						<h2>Trending Brands</h2>
						<motion.div variants={animation[1]} className={styles.imageDisplay}>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/otherImages/Pull-Bear-logo.png"
										alt="Brands Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="contain"
									></Image>
								</a>
							</Link>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/otherImages/Playstation-logo.png"
										alt="Brands Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="contain"
									></Image>
								</a>
							</Link>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/otherImages/nike-hp-logos-256x256.webp"
										alt="Brands Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="contain"
									></Image>
								</a>
							</Link>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/otherImages/puma-logo.png"
										alt="Brands Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="contain"
									></Image>
								</a>
							</Link>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/otherImages/Adidas-logo.png"
										alt="Brands Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="contain"
									></Image>
								</a>
							</Link>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/otherImages/Vans-logo.png"
										alt="Brands Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="contain"
									></Image>
								</a>
							</Link>
						</motion.div>
					</div>

					{/* <!--===== JOIN COMMUNITY =====--> */}
					<div className={styles.joinCommunity}>
						<h2>Join Our Exclusive Community</h2>
						<newButton>
							<Link href="#" target="blank">
								<a>Join Now</a>
							</Link>
						</newButton>
					</div>
				</div>
			</main>
		</motion.div>
	);
};

export default New;
