/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Footer from "/components/Footer";
import styles from "/styles/Home.module.scss";
import CrossbagproductsDB from "../lib/crossbagproductsDB.json";
// import ShoeproductsDB from "../lib/shoeproductsDB.json";

const store = () => {
	return (
		<div>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>Store | ToddBlue</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/otherImages/ms-icon-310x310.jpg" />

				{/* <!-- AOS CDN.js Reveal Animation  --> */}
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
					integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
					crossOrigin="anonymous"
					referrerpolicy="no-referrer"
				/>
				{/* <!-- Bootstrap CSS --> */}
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
					crossOrigin="anonymous"
				/>
				{/* <!-- Bootstrap Icon Link --> */}
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
				/>
				{/* <!-- Icons for Mobile viewport --> */}
				<link
					rel="stylesheet"
					href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
				/>
			</Head>

			<main className={styles.main}>
				{/* <!--===== NAVIGATION =====--> */}
				<Navbar />

				{/* <!--===== POPULAR =====--> */}
				<div className={styles.store}>
					<div className={styles.borderLineMid}></div>

					<div className={styles.productDisplay}>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								{/* <img src="/productImages/_MG_2936.jpg" alt="Product Image" /> */}
								<Image
									src="/productImages/_MG_3143-2.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Fire Force - Shinra Kusakabe
									</a>
									<h2 className={styles.price}> £109.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3103.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										My Neighbor Totoro
									</a>
									<h2 className={styles.price}> £169.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_2330.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Tanjiro, Zenitsu & Inosuke
									</a>
									<h2 className={styles.price}> £189.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3070.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										One Punch Man - Garou
									</a>
									<h2 className={styles.price}> £159.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								{/* <img src="/productImages/_MG_2936.jpg" alt="Product Image" /> */}
								<Image
									src="/productImages/_MG_2619.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Naruto - Sasuke Uchiha
									</a>
									<h2 className={styles.price}> £169.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3021.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Dragon Ball Z - Goku Vs Vegeta
									</a>
									<h2 className={styles.price}> £119.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_2778.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Spirited Away Castle
									</a>
									<h2 className={styles.price}> £189.99</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3090.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Powerpuff Girls
									</a>
									<h2 className={styles.price}> £149.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								{/* <img src="/productImages/_MG_2936.jpg" alt="Product Image" /> */}
								<Image
									src="/productImages/_MG_1629-3.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Studio Ghibli - Spirited Away
									</a>
									<h2 className={styles.price}> £189.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3269.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Demon Slayer - Tanjiro
									</a>
									<h2 className={styles.price}> £159.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3644.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Haikyuu!! - Tetsuro Kuroo
									</a>
									<h2 className={styles.price}> £169.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3441.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Haikyuu!!
									</a>
									<h2 className={styles.price}> £149.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								{/* <img src="/productImages/_MG_2936.jpg" alt="Product Image" /> */}
								<Image
									src="/productImages/_MG_3295.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Spider-Man: Miles Morales
									</a>
									<h2 className={styles.price}> £199.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3551 - Copy.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Demon Slayer - Mitsuri Kanroji
									</a>
									<h2 className={styles.price}> £179.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_3482.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Sakura, Naruto, Sasuke
									</a>
									<h2 className={styles.price}> £179.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								<Image
									src="/productImages/_MG_2538.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Hunter × Hunter - Killua Zoldyck
									</a>
									<h2 className={styles.price}> £149.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<a href="#" target="blank">
								{/* <img src="/productImages/_MG_2936.jpg" alt="Product Image" /> */}
								<Image
									src="/productImages/_MG_2687.jpg"
									alt="Product Image"
									width={200}
									height={200}
									layout="responsive"
									objectFit="cover"
								/>
							</a>

							<div className={styles.description}>
								<div className={styles.topSection}>
									<a href="#" target="blank">
										Ochaco Uraraka
									</a>
									<h2 className={styles.price}> £169.95</h2>
								</div>
								<a href="#" target="blank" className={styles.productCategory}>
									Men & Womens
								</a>
							</div>
						</div>
						<div className={styles.productItem}>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/productImages/_MG_3254.jpg"
										alt="Product Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="cover"
									/>
								</a>
							</Link>
							<div className={styles.description}>
								<div className={styles.topSection}>
									<Link href="#" target="blank">
										<a>{CrossbagproductsDB[0].productName}</a>
									</Link>
									<h2 className={styles.price}>
										{CrossbagproductsDB[0].pricing}
									</h2>
								</div>
								<Link
									href="/"
									target="blank"
									className={styles.productCategory}
								>
									<a>{CrossbagproductsDB[0].productCategory}</a>
								</Link>
							</div>
						</div>
						<div className={styles.productItem}>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/productImages/_MG_1881.jpg"
										alt="Product Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="cover"
									/>
								</a>
							</Link>
							<div className={styles.description}>
								<div className={styles.topSection}>
									<Link href="#" target="blank">
										<a>{CrossbagproductsDB[1].productName}</a>
									</Link>
									<h2 className={styles.price}>
										{CrossbagproductsDB[1].pricing}
									</h2>
								</div>
								<Link
									href="/"
									target="blank"
									className={styles.productCategory}
								>
									<a>{CrossbagproductsDB[1].productCategory}</a>
								</Link>
							</div>
						</div>
						<div className={styles.productItem}>
							<Link href="#" target="blank">
								<a>
									<Image
										src="/productImages/_MG_1890.jpg"
										alt="Product Image"
										width={200}
										height={200}
										layout="responsive"
										objectFit="cover"
									/>
								</a>
							</Link>
							<div className={styles.description}>
								<div className={styles.topSection}>
									<Link href="#" target="blank">
										<a>{CrossbagproductsDB[2].productName}</a>
									</Link>
									<h2 className={styles.price}>
										{CrossbagproductsDB[2].pricing}
									</h2>
								</div>
								<Link
									href="/"
									target="blank"
									className={styles.productCategory}
								>
									<a>{CrossbagproductsDB[2].productCategory}</a>
								</Link>
							</div>
						</div>
					</div>

					<div className={styles.borderLineMid}></div>

					{/* <!--===== RELATED CATEGORY =====--> */}
					<div className={styles.bottomContent}>
						<div className={styles.relatedCategories}>
							<h2>Related Categories</h2>

							<div className={styles.list}>
								<ul className={styles.links}>
									<Link href="#" target="blank">
										<a>Mens Clothing</a>
									</Link>
									<Link href="#" target="blank">
										<a>Womens Clothing</a>
									</Link>
									<Link href="#" target="blank">
										<a>Backpacks & Bags</a>
									</Link>
									<Link href="#" target="blank">
										<a>Cross-Body Bags</a>
									</Link>
								</ul>
							</div>
						</div>
						<div className={styles.relatedStories}>
							<h2>Help Guide Stories</h2>

							<div className={styles.content}>
								<div className={styles.productGuide}>
									<a href="#" target="blank">
										{/* <img src="/productImages/_MG_2936.jpg" alt="Product Image" /> */}
										<Image
											src="/otherImages/a6da69b3cbefc0b7d1c3e9f67d011f8a.jpg"
											alt="Product Image"
											width={500}
											height={500}
											layout="responsive"
											objectFit="cover"
										/>
									</a>

									<h5>Size Guide</h5>
									<h2>How to select the right shoe size.</h2>
								</div>
								<div className={styles.productGuide}>
									<a href="#" target="blank">
										{/* <img src="/productImages/_MG_2936.jpg" alt="Product Image" /> */}
										<Image
											src="/otherImages/dca9766ecf88354b6b32ea3c48b6e7cb.jpg"
											alt="Product Image"
											width={500}
											height={500}
											layout="responsive"
											objectFit="cover"
										/>
									</a>

									<h5>Buying Guide</h5>
									<h2>How to select the right item.</h2>
								</div>
								<div className={styles.productGuide}>
									<a href="#" target="blank">
										{/* <img src="/productImages/_MG_2936.jpg" alt="Product Image" /> */}
										<Image
											src="/otherImages/c7e6d1df7824762ba1395ea8db3978d2.jpg"
											alt="Product Image"
											width={500}
											height={500}
											layout="responsive"
											objectFit="cover"
										/>
									</a>

									<h5>Backpacks & Bags Guide</h5>
									<h2>Which is the right Backpacks or Bags for the event.</h2>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>

			{/* <!--===== FOOTER =====--> */}
			<Footer />
		</div>
	);
};

export default store;
